{
    "name": "النجوم",
    "price": 0,
    "colors": {
        "background": "0f1f3dff",
        "foreground": "f2f2f2ff",
        "buttons": [
            "4cd4aeff",
            "ffd700ff",
            "2389fcff",
            "d94848ff"
        ],
        "empty_cell": "26355cff",
        "cells": [
            "4cd4aeff", "98dc53ff", "5abee2ff",
            "fec63dff", "ec9548ff", "e66a82ff",
            "7988bfff", "da6554ff", "57cb84ff"
        ],
        "current_score": "ffcc00ff",
        "high_score": "65d681ff",
        "bonus": "d4d4d4ff",
        "band": "48cae4ff",
        "text": "f2f2f2ff"
    },
    "cell_texture": "basic.png"
}
